config/routes.rb
Rails.application.routes.draw do



  get 'users/show'

  get 'likes/index'

  resources :topics

  resources :topics, only: [] do
    resources :bookmarks, except: [:index, :show]
  end

  resources :bookmarks, except: [:index] do
    resources :likes, only: [:create, :destroy]
  end

  root 'welcome#index'
  post :incoming, to: 'incoming#create'
  devise_for :users
  resources :users, only: [:show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :topic
  belongs_to :user
end

app/models/concerns/application_mailer.rb
class ApplicationMailer < ActionMailer::Base
  default from: 'from@example.com'
  layout 'mailer'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :bookmark
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :topics
  has_many :bookmarks, dependent: :destroy
  has_many :likes, dependent: :destroy

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
    user_params.permit({ roles: [] }, :username, :email, :password, :password_confirmation)
    end
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to root_path
  end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new
    authorize @bookmark
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = @topic.bookmarks.build(bookmark_params)
    @bookmark.user = current_user
    authorize @bookmark

    if @bookmark.save
      redirect_to @topic, notice: "Bookmark was saved successfully."
    else
      flash.now[:alert] = "Error creating bookmark. Please try again."
      render :new
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    @bookmark.assign_attributes(bookmark_params)
    authorize @bookmark

    if @bookmark.save
      flash[:notice] = "Bookmark was updated."
       redirect_to @bookmark.topic
     else
       flash.now[:alert] = "There was an error saving the bookmark. Please try again."
       render :edit
     end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark

    if @bookmark.destroy
      flash[:notice] = "bookmark deleted"
      redirect_to [@bookmark.topic, @bookmark]
    else
      flash[:alert] = "There was an error deleting this bookmark"
    end
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:url)
  end

end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]

 def create
   @user = User.find_by(params[:sender])
   @topic = Topic.find_by(params[:subject])
   @url = params[:body-plain]

   if @user.nil?
     @user = User.create(email: params[:sender], password: "blocmarks")
   end

   if @topic.nil?
     @topic = Topic.create(title: params[:subject], user_id: @user)
   end

   @bookmark = @topic.bookmarks.create(url: @url)

   puts "user - #{@user}, topic - #{@topic}, url - #{@url}"

   head 200

 end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def index
    @likes = Like.all
  end

  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.build(bookmark: @bookmark)

    if like.save
      flash[:notice] = "You liked this site - #{@bookmark.url}"

     else
       flash.now[:alert] = "There was an error liking the site"
     end
     redirect_to @bookmark.topic
  end

  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.find(params[:id])

    if like.destroy
      flash[:notice] = "Unliked site"
     else
       flash.now[:alert] = "There was an error unliking site"
     end
     redirect_to [@bookmark.topic]


  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
    # @bookmark = Bookmark.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @user = current_user
    @topic = @user.topics.build(topic_params)
    @topic.user = current_user

    if @topic.save
      redirect_to @topic, notice: "Topic was saved successfully."
    else
      flash.now[:alert] = "Error creating topic. Please try again."
      render :new
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    if @topic.destroy
      flash[:notice] = "topic deleted"
      redirect_to topics_path
    else
      flash[:alert] = "There was an error deleting this topic"
    end
    puts "topic destroy from controller"
  end

  def edit
  end
end

private
  def topic_params
    params.require(:topic).permit(:title)
  end



# mjthompsgb+test4@gmail.com
# @sink.sendgrid.net
# %w(google.com yahoo.com facebook.com)

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    if current_user.present?
      @user = params[:id] ? User.find(params[:id]) : current_user
      @user_bookmarks = @user.bookmarks
      @liked_bookmarks = @user.likes
    else
      redirect_to new_user_registration_path
    end

  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/incoming_helper.rb
module IncomingHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/_form.html.erb
<div class="col-md-8">
  <%= form_for [topic, bookmark] do |f| %>
    <div class="form-group">
      <%= f.label :url %>
      <%= f.text_field :url, class: 'form-control', placeholder: "Enter url" %>
    </div>
    <%= f.submit "Save", class: 'btn btn-success' %>
  <% end %>
</div>

app/views/bookmarks/_list.html.erb
<div class="row">
  <% topic.bookmarks.each do |bookmark| %>
  <div class="col-sm-8">
    <div class="well bookmark_box">
      <%= bookmark.url %> <br>
      <%= link_to "Delete", bookmark, method: :delete, class: 'glyphicon glyphicon-remove-circle', data: { confirm: "Are you sure you want to delete this bookmark?" } %> <br>
      <%= link_to "Edit", edit_bookmark_path(bookmark), class: 'glyphicon glyphicon-pencil' %>
    </div>
    <div class="button_placement">
    <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
    </div>
  </div>
  <% end %>
</div>
<br>
<br>
<div>
  <p> Bottom of page </p>
</div>

app/views/bookmarks/_thumbnail.html.erb
<strong> <%= link_to bookmark.url.upcase, bookmark.url %> </strong>
<a href=https://<%= bookmark.url %>><img src="http://img.bitpixels.com/getthumbnail?code=71093&size=200&url=<%= bookmark.url %>" /></a>

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/edit.html.erb
<div class='row'><br>
    <h2> Edit Bookmark </h2>
      <div class="col-md-8">
        <div class="col-md-8">
          <%= form_for [@bookmark.topic, @bookmark], method: "put" do |f| %>
            <div class="form-group">
              <%= f.label :url %>
              <%= f.text_field :url, class: 'form-control', placeholder: "Enter url" %>
            </div>
            <%= f.submit "Save", class: 'btn btn-success' %>
          <% end %>
        </div>
      </div>
</div>

app/views/bookmarks/index.html.erb
<h1>Bookmarks#index</h1>
<p>Find me in app/views/bookmarks/index.html.erb</p>

app/views/bookmarks/new.html.erb
<div class='row'><br>
    <h2> Add Bookmark </h2>
      <div class="col-md-8">
        <div class="col-md-8">
          <%= form_for [@topic, @bookmark] do |f| %>
            <div class="form-group">
              <%= f.label :url %>
              <%= f.text_field :url, class: 'form-control', placeholder: "Enter url" %>
            </div>
            <%= f.submit "Save", class: 'btn btn-success' %>
          <% end %>
        </div>
      </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SiteShare</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
    <ul class='nav nav-tabs'>
      <% if user_signed_in? %>
       <li><%= link_to "Bookmarks", topics_path %></li>
       <li><%= link_to "My Bookmarks", user_path(current_user) %></li>
      <% end %>
       <li> <%= link_to "Home", root_path %></li>
       <li> </li>
     </ul>
    <% if user_signed_in? %>
     Signed in as: <strong><%= current_user.username %></strong> |
     <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
     <% else %>
     <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
     <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
   <% end %>
   <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/likes/_like.html.erb
<div>
  <% if like = current_user.liked(bookmark) %>
    <%= link_to [bookmark, like], class: 'btn btn-danger', method: :delete do %>
      <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Unlike
    <% end %>
  <% else %>
    <%= link_to [bookmark, Like.new], class: 'btn btn-primary', method: :post do %>
      <i class="glyphicon glyphicon-star"> </i>&nbsp; Like
    <% end %>
  <% end %>
</div>

app/views/likes/index.html.erb
<h1>Likes#index</h1>
<p>Find me in app/views/likes/index.html.erb</p>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<h1>Topics</h1>


<div class='row'>
  <div>
    <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
  </div>
  <br>
  <div class="col-md-8">
       <% @topics.each do |topic| %>
         <div class="media">
           <div class="media-body">
             <h3 class="media-heading">
               <%= link_to topic.title, topic %> <br>
               <%= link_to "Delete", [@user, topic], method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure you want to delete topic?"} %>
             </h3>
             <small> created
               <%= time_ago_in_words(topic.created_at) %> ago
             </small>
           </div>
         </div>
       <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter topic name" %>
      </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<div class="row"><br>
    <div class="col-md-8">
        <p class="lead">
          <h2>
          <%= @topic.title %> <br>
        </h2>
          <%= link_to "Delete topic", [@topic], method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure you want to delete topic?"} %>
          <%= link_to "New Bookmark", new_topic_bookmark_path(@topic, @bookmark), class: 'btn btn-success' %>
        </p>
        <div>
        <%= render partial: 'bookmarks/list', locals: { topic: @topic } %>
        <div>
    </div>
</div>

app/views/users/show.html.erb
<h1> My Blocmarks </h1>

<h2> <%= @user.username %>'s Bookmarks </h2>

  <div class="row">
    <% @user_bookmarks.each do |bookmark| %>
    <div class="col-sm-4">
      <div class="well bookmark_box">
        <%= render partial: 'bookmarks/thumbnail', locals: { bookmark: bookmark } %>
        <br>
        <%= link_to "Delete", bookmark, method: :delete, class: 'glyphicon glyphicon-remove-circle', data: { confirm: "Are you sure you want to delete this bookmark?" } %> <br>
        <%= link_to "Edit", edit_bookmark_path(bookmark), class: 'glyphicon glyphicon-pencil' %>
      </div>
      <div class="button_placement">
      <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
      </div>
    </div>
    <% end %>
  </div>
______________________

<h2> Liked Bookmarks </h2>

<div class="row">
  <% @liked_bookmarks.each do |like| %>
  <div class="col-sm-4">
    <div class="well bookmark_box">
      <%= render partial: 'bookmarks/thumbnail', locals: { bookmark: like.bookmark } %>

    </div>
    <div class="button_placement">
    <%= render partial: 'likes/like', locals: { bookmark: like.bookmark } %>
    </div>
  </div>
  <% end %>
</div>
<br>
<br>
<br>
<div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to SiteShare</h1>
<p>Share your bookmarks with friends</p>